// Copyright (c) 2015 Titanium I.T. LLC. All rights reserved. See LICENSE.txt for details.
(function() {
	"use strict";

	// This file is generated by pre-compiling .hbs files in the build script.
	var templates = require("./templates.js");

	// This custom resolver tells Ember how to get templates out of the 'templates' module.
	var CommonJsResolver = Ember.DefaultResolver.extend({
		resolveTemplate: function(parsedName) {
			var template = templates[parsedName.fullNameWithoutType];
			if (!template) template = this._super(parsedName);
			return template;
		}
	});

	var App = module.exports = Ember.Application.create({
		Resolver: CommonJsResolver
	});

	App.ExampleApplicationComponent = require("./ui/example_application.js");

	App.ConfigurationPanelComponent = require("./ui/configuration_panel.js");
	App.ConfigurationFieldComponent = require("./ui/configuration_field.js");

	App.StockMarketTableComponent = require("./ui/stock_market_table.js");
	App.StockMarketRowComponent = require("./ui/stock_market_row.js");
	App.StockMarketCellComponent = require("./ui/stock_market_cell.js");

}());