// Copyright (c) 2015 Titanium I.T. LLC. All rights reserved. See LICENSE.txt for details.
(function() {
	"use strict";

	// This file is generated by pre-compiling .hbs files in the build script.
	var templates = require("./templates.js");

	// This customer resolver tells Ember how to get templates out of the 'templates' module.
	var CommonJsResolver = Ember.DefaultResolver.extend({
		resolveTemplate: function(parsedName) {
			var template = templates[parsedName.fullNameWithoutType];
			if (!template) template = this._super(parsedName);
			return template;
		}
	});

	var App = exports.module = Ember.Application.create({
		Resolver: CommonJsResolver
	});
	App.StockMarketRowComponent = require("./ui/stock_market_row.js");

}());